// Generated by CoffeeScript 1.11.1
var clean, spacesToTabs, transpile;

spacesToTabs = function(line) {
  if (line.indexOf('  ') === 0) {
    return '\t' + spacesToTabs(line.substring(2));
  }
  if (line.indexOf('\t') === 0) {
    return '\t' + spacesToTabs(line.substring(1));
  }
  if (line.indexOf(' \t') === 0) {
    return '\t' + spacesToTabs(line.substring(2));
  }
  return line;
};

clean = function(s) {
  var pos;
  s = s.split(' ').join("");
  s = s.split('\t').join("");
  pos = s.indexOf("#");
  if (pos >= 0) {
    s = s.substr(0, pos);
  }
  return s;
};

transpile = function(code) {
  var i, len, line, lines, temp;
  lines = code.split('\n');
  if (lines[0].indexOf('//ECMA') === 0) {
    return code;
  }
  temp = ['class Student'];
  for (i = 0, len = lines.length; i < len; i++) {
    line = lines[i];
    line = "\t" + spacesToTabs(line);
    if (clean(line).length > 0) {
      temp.push(line);
    }
  }
  temp.push("@xstudent = new Student()");
  code = temp.join('\n');
  return CoffeeScript.compile(code, {
    bare: true
  });
};
